Name = "alifeee's webring!"
Description = "For the glory of the Indieweb!"
Root = "https://webring.alifeee.co.uk"

[[Websites]]
Name = "alifeee's website!!!"
Url = "https://alifeee.co.uk"
Image = "https://alifeee.co.uk/og-image.jpg"
Description = "a blog! simulations! tools! data! bookmarks! a collection of madness from the mind of alifeee"

[[Websites]]
Name = "neilgaryallen's blog"
Url = "https://neilgaryallen.dev"
Image = "https://neilgaryallen.dev/neil.jpg"
Description = "neil gary allen takes things apart"

[[Websites]]
Name = "Alex Adler - a project"
Url = "https://adler.robertoholm.es/"
Image = "https://alex-adler.github.io/favicon/favicon.svg"
Description = "Engineering for the near future"

[[Websites]]
Name = "Ray's Miscellany"
Url = "https://brisray.com/"
Image = "https://brisray.com/images/ray-disguise-938-20150721-web200.jpg"
Description = "Stuff I'm interested in"
